### ISSUE TITLE
Conflicting dependencies with Django 4.0

### ISSUE THREAD

**Issue by toniengelhardt** [zsoldosp/django-currentuser#58]
```bash
ERROR: Cannot install -r requirements.txt, Django==4.0 and django-currentuser==0.5.3 because these package versions have conflicting dependencies.

The conflict is caused by:
    django-currentuser 0.5.3 depends on Django<3.3 and >=1.11.17; python_version >= "2.7"
```

Is this just a matter of adjusting the dependency requirement or are there any changes needed in the package?

**Comment by N1K1TAS95** [comment]
Same here. Django 4.0 support needed.

**Comment by N1K1TAS95** [comment]
Any updates?

**Comment by asucrews** [comment]
I created a PR with 58, 61, and support for Django 4.0

@toniengelhardt, @M3te0r, and @N1K1TAS95

**Comment by bernd-wechner** [comment]
Go with this in `requirements.txt`:
```
django-currentuser @ https://github.com/asucrews/django-currentuser/archive/refs/heads/master.zip
```

**Comment by dannwise** [comment]
@bernd-wechner thank you!

**Comment by SachidanandAlle** [comment]
> Go with this in `requirements.txt`:
> 
> ```
> django-currentuser @ https://github.com/asucrews/django-currentuser/archive/refs/heads/master.zip
> ```

Will be helpful if the owner can push the latest version of PIP package for public use.  Thanks :)

**Comment by melboone** [comment]
Thanks

**Comment by shitalkuhikar** [comment]
Go with this in `requirements.txt`:

django-currentuser @ https://github.com/asucrews/django-currentuser/archive/refs/heads/master.zip

This was working till yesterday, but now url does not work. Is there any work around.

**Comment by shitalkuhikar** [comment]
django-currentuser @ https://github.com/asucrews/django-currentuser/archive/refs/heads/master.zip
Above url not working from yesterday

**Comment by varzgalys** [comment]
The owner has changed, change URL to 
`django-currentuser @ https://github.com/zsoldosp/django-currentuser/archive/refs/heads/master.zip`

**Comment by zsoldosp** [comment]
FYI, 0.6.0 / 0.6.1 have just been released on pypi adding support for the current django versions. see #70
