### ISSUE TITLE
support for django 4

### ISSUE THREAD

**Issue by kemalbastak** [zsoldosp/django-currentuser#65]
cannot update the django version 3.0 to 4.1

**Comment by jongracecox** [comment]
There is a similar issue, #58, which may contain useful info on using django-currentuser with Django 4.

**Comment by Przemek625** [comment]
@konstantinpae Can you merge this please?

**Comment by zsoldosp** [comment]
#62 solved it, #68 will make a pypi relase

**Comment by zsoldosp** [comment]
FYI, 0.6.0 / 0.6.1 have just been released on pypi adding support for the current django versions. see #70
