### ISSUE TITLE
make initial release after the repo's transfer

### ISSUE THREAD

**Issue by zsoldosp** [zsoldosp/django-currentuser#68]

**Comment by maltalk** [comment]
Hi!
Thank for all the work done here!
Could we have an approximate date for the release?

**Comment by zsoldosp** [comment]
@maltalk due to summer holiday season, the pypi project transfer hasn't happened yet. Once I have that, I'll post an update to this issue

**Comment by zsoldosp** [comment]
FYI, I got ownership of the project on pypi too. 🎉  Given my other commitments, I'll start working on making the release in ~10 days

**Comment by Sharashchandra** [comment]
@zsoldosp Hey, any updates on when the release would be done to pypi?

**Comment by zsoldosp** [comment]
I'm thinking early next week, but it's a FYI not a commitment :-)

summer is a hard time for free time

**Comment by Sharashchandra** [comment]
Thanks for the update!

**Comment by zsoldosp** [comment]
FYI, 0.6.0 / 0.6.1 have just been released on pypi adding support for the current django versions. see #70
