### ISSUE TITLE
Support for Django 5.1

### ISSUE THREAD

**Issue by peterkronenberg** [zsoldosp/django-currentuser#75]
Will you soon be supporting Django 5.1?

**Comment by zsoldosp** [comment]
Yes, the soonest next week

**Comment by anyidea** [comment]
any progress?

**Comment by zsoldosp** [comment]
I just released the [new version to pypi](https://pypi.org/project/django-currentuser/0.8.0/). 

Note the introduction of `DJANGO_CURRENTUSER_USE_UNSUPPORTED_DJANGO` to make future app upgrades smoother. For more details, see the README's install section.
